export const HOTEL_POLICIES = {
  checkIn: '14:00', // 2:00 PM
  checkOut: '12:00', // 12:00 PM
  earlyCheckIn: 'Subject to availability',
  lateCheckOut: 'Available for additional fee',
  
  children: {
    allowed: true,
    ageLimit: 'All ages welcome',
    extraBeds: false,
    cribs: false,
    policy: 'Children of all ages are welcome. Add number and ages for correct pricing.',
  },
  
  pets: {
    allowed: false,
    policy: 'Pets are not allowed',
  },
  
  smoking: {
    allowed: false,
    designatedAreas: true,
    policy: 'Smoking is not allowed in rooms. Designated smoking areas available.',
  },
  
  payment: {
    methods: ['Credit Card', 'Debit Card', 'Cash'],
    currencies: ['AZN', 'USD', 'EUR'],
    deposit: 'Security deposit may be required',
  },
  
  cancellation: {
    policy: 'Varies by room type and rate',
    freeCancellation: 'Available on selected rates',
    note: 'Check specific conditions when booking',
  },
} as const;

export const DINING_VENUES = [
  {
    id: 'terrace',
    name: 'The Terrace Restaurant',
    type: 'Restaurant',
    cuisine: ['International', 'Italian', 'Mexican'],
    hours: {
      breakfast: '07:00 - 10:30',
      lunch: '12:30 - 15:00',
      dinner: '19:00 - 22:30',
    },
    features: ['Buffet Breakfast', 'À la carte', 'Sea View', 'Outdoor Seating'],
    description: 'Main restaurant serving buffet breakfast and international cuisine with Italian and Mexican specialties',
  },
  {
    id: 'wild-west',
    name: 'Wild West Bar',
    type: 'Bar',
    cuisine: ['Bar Snacks', 'Cocktails'],
    hours: {
      daily: '17:00 - 02:00',
    },
    features: ['Live Music', 'Cocktails', 'Theme Nights'],
    description: 'Western-themed bar with live entertainment and extensive cocktail menu',
  },
  {
    id: 'shade-bar',
    name: 'Shade Bar',
    type: 'Poolside Bar',
    cuisine: ['Light Bites', 'Beverages'],
    hours: {
      daily: '10:00 - 20:00',
    },
    features: ['Poolside', 'Cocktails', 'Snacks', 'Fresh Juices'],
    description: 'Relaxing poolside bar serving refreshing drinks and light snacks',
  },
  {
    id: 'pool-bar',
    name: 'Pool Bar',
    type: 'Bar',
    cuisine: ['Snacks', 'Beverages'],
    hours: {
      daily: '10:00 - 18:00',
    },
    features: ['Swimming Pool View', 'Light Meals', 'Cocktails'],
    description: 'Casual bar by the pool offering drinks and light fare',
  },
] as const;

export const NEARBY_ATTRACTIONS = [
  {
    name: 'Bibiheybat Mosque',
    distance: '1.7 km',
    type: 'Religious Site',
    description: 'Historic mosque and important pilgrimage site',
  },
  {
    name: 'Carpet Museum',
    distance: '6.6 km',
    type: 'Museum',
    description: 'Showcasing Azerbaijan\'s carpet weaving heritage',
  },
  {
    name: 'Baku City Circuit',
    distance: '7.5 km',
    type: 'Sports Venue',
    description: 'Formula 1 Azerbaijan Grand Prix street circuit',
    driveTime: '9 minutes',
  },
  {
    name: 'Flame Towers',
    distance: '8.5 km',
    type: 'Landmark',
    description: 'Iconic skyscrapers and symbol of modern Baku',
    driveTime: '9 minutes',
  },
  {
    name: 'Nizami Street',
    distance: '9.2 km',
    type: 'Shopping',
    description: 'Main pedestrian shopping street in downtown Baku',
    driveTime: '10 minutes',
  },
  {
    name: 'National Flag Square',
    distance: '6 km',
    type: 'Landmark',
    description: 'Home to one of the world\'s tallest flagpoles',
  },
  {
    name: 'Heydar Aliyev Airport',
    distance: '40 km',
    type: 'Airport',
    description: 'Main international airport',
    driveTime: '35-40 minutes',
  },
  {
    name: 'Baku City Center',
    distance: '8.9 km',
    type: 'City Center',
    description: 'Downtown Baku with shops, restaurants, and attractions',
    driveTime: '10 minutes',
  },
] as const;

export const ROOM_CATEGORIES = [
  {
    id: 'standard-single',
    category: 'Standard',
    name: 'Standard Single Room',
    capacity: 1,
    size: 22,
    bedType: 'Single Bed',
    view: 'City View',
    price: 120,
    features: [
      'Air Conditioning',
      'Flat-screen TV',
      'Free WiFi',
      'Minibar',
      'Safe',
      'Desk',
      'Private Bathroom',
      'Shower',
      'Hair Dryer',
      'Toiletries',
      'Tea/Coffee Maker',
      'Soundproof Walls',
    ],
  },
  {
    id: 'standard-twin',
    category: 'Standard',
    name: 'Standard Twin Room',
    capacity: 2,
    size: 26,
    bedType: 'Two Single Beds',
    view: 'Garden View',
    price: 150,
    features: [
      'Air Conditioning',
      'Flat-screen TV',
      'Free WiFi',
      'Minibar',
      'Safe',
      'Desk',
      'Private Bathroom',
      'Shower',
      'Hair Dryer',
      'Toiletries',
      'Tea/Coffee Maker',
      'Soundproof Walls',
    ],
  },
  {
    id: 'deluxe-sea-view',
    category: 'Deluxe',
    name: 'Deluxe Sea View Room',
    capacity: 2,
    size: 32,
    bedType: 'King Size Bed',
    view: 'Sea View',
    price: 220,
    features: [
      'Air Conditioning',
      'Flat-screen TV',
      'Free WiFi',
      'Minibar',
      'Safe',
      'Desk',
      'Private Bathroom',
      'Bath & Shower',
      'Bathrobes',
      'Slippers',
      'Hair Dryer',
      'Premium Toiletries',
      'Tea/Coffee Maker',
      'Balcony',
      'Sea View',
      'Soundproof Walls',
      'Seating Area',
    ],
  },
  {
    id: 'family-suite',
    category: 'Suite',
    name: 'Family Suite',
    capacity: 4,
    size: 45,
    bedType: 'King Bed + Sofa Bed',
    view: 'Sea View',
    price: 350,
    features: [
      'Air Conditioning',
      'Flat-screen TV (2)',
      'Free WiFi',
      'Minibar',
      'Safe',
      'Desk',
      'Living Area',
      'Private Bathroom',
      'Bath & Shower',
      'Bathrobes',
      'Slippers',
      'Hair Dryer',
      'Premium Toiletries',
      'Tea/Coffee Maker',
      'Balcony',
      'Sea View',
      'Soundproof Walls',
      'Dining Area',
    ],
  },
] as const;

export const LANGUAGES_SPOKEN = ['English', 'Azerbaijani', 'Russian'] as const;

export const HOTEL_FEATURES = {
  beachLength: '400+ meters',
  privateBeach: true,
  yearEstablished: 2000,
  lastRenovation: 2023,
  totalRooms: 260,
  floors: 8,
  rating: 7.9,
  reviewCount: 46,
  starRating: 4,
  certifications: [],
} as const;