export const GUEST_REVIEWS = [
  {
    id: 1,
    author: 'Sarah Mitchell',
    country: 'United Kingdom',
    rating: 9,
    date: '2024-10',
    stayType: 'Family',
    title: 'Fantastic family vacation',
    comment: 'Pleasant staff, great service, excellent location. Rooms are very clean and mattress is very comfy. The hotel has private beach which is very convenient! The facilities were fantastic, the hotel had everything we needed.',
    pros: ['Private beach', 'Clean rooms', 'Friendly staff', 'Great location'],
    cons: [],
    helpfulCount: 12,
    verified: true,
  },
  {
    id: 2,
    author: 'Ahmed Hassan',
    country: 'UAE',
    rating: 8,
    date: '2024-09',
    stayType: 'Business',
    title: 'Great for business and leisure',
    comment: 'The hotel has a very nostalgic and wholesome vibe to it which we really enjoyed as a family. Only 10 minutes from city center but feels like a private retreat. Business center was well-equipped.',
    pros: ['Close to city', 'Business facilities', 'Quiet atmosphere', 'Good WiFi'],
    cons: ['Limited parking during events'],
    helpfulCount: 8,
    verified: true,
  },
  {
    id: 3,
    author: 'Maria Rodriguez',
    country: 'Spain',
    rating: 8.5,
    date: '2024-08',
    stayType: 'Couple',
    title: 'Romantic getaway by the sea',
    comment: 'Beautiful beachfront property with amazing sunset views. The Terrace Restaurant has excellent Italian food. Spa services were relaxing and professional.',
    pros: ['Beach access', 'Romantic setting', 'Great food', 'Spa services'],
    cons: ['Some areas need renovation'],
    helpfulCount: 15,
    verified: true,
  },
  {
    id: 4,
    author: 'Vladimir Petrov',
    country: 'Russia',
    rating: 7.5,
    date: '2024-07',
    stayType: 'Family',
    title: 'Good family resort',
    comment: 'Kids loved the pools and beach. Multiple dining options kept everyone happy. Staff speaks Russian which was helpful. The bowling and mini golf were nice additions.',
    pros: ['Kid-friendly', 'Multiple pools', 'Beach activities', 'Russian-speaking staff'],
    cons: ['Crowded during summer', 'Some facilities dated'],
    helpfulCount: 6,
    verified: true,
  },
  {
    id: 5,
    author: 'James Wilson',
    country: 'Australia',
    rating: 9,
    date: '2024-06',
    stayType: 'Solo',
    title: 'Exceeded expectations',
    comment: 'First time in Baku and this hotel made it memorable. The private beach is stunning, rooms are spacious and clean. Wild West Bar has great live music. Airport shuttle was convenient.',
    pros: ['Spacious rooms', 'Live entertainment', 'Airport shuttle', 'Beach quality'],
    cons: [],
    helpfulCount: 20,
    verified: true,
  },
  {
    id: 6,
    author: 'Fatima Al-Rashid',
    country: 'Saudi Arabia',
    rating: 8,
    date: '2024-05',
    stayType: 'Family',
    title: 'Perfect for families',
    comment: 'Large rooms perfect for families. Private beach meant kids could play safely. Multiple restaurants catered to different tastes. Staff very accommodating to special requests.',
    pros: ['Family rooms', 'Safe beach', 'Variety of food', 'Helpful staff'],
    cons: ['AC could be better in summer'],
    helpfulCount: 11,
    verified: true,
  },
];

export const REVIEW_SUMMARY = {
  averageRating: 7.9,
  totalReviews: 46,
  ratingDistribution: {
    5: 8,
    4: 15,
    3: 18,
    2: 4,
    1: 1,
  },
  categories: {
    location: 8.5,
    cleanliness: 8.2,
    service: 8.0,
    comfort: 7.8,
    facilities: 7.6,
    value: 7.5,
  },
  reviewerTypes: {
    families: '45%',
    couples: '25%',
    business: '20%',
    solo: '10%',
  },
};